"""Initial migration

Revision ID: 69fea7f47ca5
Revises: 
Create Date: 2025-02-15 17:46:30.300442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fea7f47ca5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profit_paid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_name', sa.String(length=200), nullable=False),
    sa.Column('date_paid', sa.String(length=10), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               nullable=True)

    op.drop_table('profit_paid')
    # ### end Alembic commands ###
